export const state = {
  user: {},
  listUser: [],
  category: {},
  listCategory: [],
  product: {},
  listProduct: [],
  order: {},
  listOrder: [],
  discount: {},
  listDiscount: [],
  cart: {},
  listCart: [],
  log: [],
  listLog: [],
  post: {},
  listPost: [],
  listDiscountProduct: [],
  showSearchResult: false,
  previewFile: [],
  uploadFile: [],
  previewFiles: [],
  uploadFiles: [],
  uploadThumbnail: [],
  previewThumbnail: [],
};
